# Generated by Django 2.0.6 on 2018-07-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artfilters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtImageFilters',
            new_name='ArtImageFilter',
        ),
        migrations.RenameModel(
            old_name='PageTitles',
            new_name='PageTitle',
        ),
    ]
