# Generated by Django 2.0.6 on 2018-07-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfilters', '0002_auto_20180709_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
