# Generated by Django 2.0.6 on 2018-07-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfilters', '0003_artimage_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='path',
            field=models.FilePathField(path='/documents_1TB_1/thomas/development/django/artsite/artfilters/static/artfilters/images'),
        ),
    ]
