# Generated by Django 2.0.6 on 2018-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfilters', '0004_auto_20180721_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='path',
            field=models.FilePathField(max_length=255, path='/documents_1TB_1/thomas/development/django/artsite/artfilters/static/artfilters/images'),
        ),
    ]
