# Generated by Django 2.1.2 on 2018-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfilters', '0005_auto_20180721_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='path',
            field=models.FilePathField(max_length=255, path='/mnt/d/development/python3_env/suchyta-art-site/artfilters/static/artfilters/images'),
        ),
    ]
